---
# defaults file for convert

convert_convert2rhel_opts: ""
convert_convert2rhel_env_vars: {}
# convert_convert2rhel_env_vars:
#   CONVERT2RHEL_ALLOW_UNAVAILABLE_KMODS: 1
#   CONVERT2RHEL_SKIP_KERNEL_CURRENCY_CHECK: 1

# If you are converting to RHEL 8.8 and have an Extended Upgrade Support (EUS), add the --eus option by setting this variable to true.
convert_convert2rhel_eus: false
convert_convert2rhel_repos_enabled: []
convert_convert2rhel_repos_disabled: []

convert_os_path: $PATH

convert_async_timeout_maximum: 7200
convert_async_poll_interval: 60
convert_reboot_timeout: 900

convert_no_rhsm: false
convert_reboot_requested: false

convert_gpg_key_remove: false
convert_convert2rhel_repo_remove: true
convert_convert2rhel_package_remove: true
...
