---
# handlers file for analysis
# Keep this last so it's easy to find in the job output.
- name: Display analysis inhibitors
  ansible.builtin.debug:
    var: convert2rhel_inhibitors_txt.stdout_lines
  when: conversion_inhibited
  listen: Pre-conversion analysis report is done

- name: Pre-conversion analysis report is done
  ansible.builtin.debug:
    msg: >-
      The pre-conversion analysis report generation is now complete.
      {{ 'WARNING: Inhibitors' if conversion_inhibited else 'SUCCESS: No inhibitors' }} found.
      Review the result file at {{ analysis_result_filename_txt }}.
...
