---
- name: Convert2RHEL Analyze
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Include sat_registration role
      ansible.builtin.include_role:
        name: sat_registration

    - name: Include convert2rhel_remediate role
      ansible.builtin.include_role:
        name: convert2rhel_remediate

    - name: Include convert2rhel_convert role
      ansible.builtin.include_role:
        name: convert2rhel_convert

...
